cluster.name: active-data
node.zone: spot
node.name: spot_{{id}}
node.master: false
node.data: true

script.inline: on
script.indexed: on


cluster.routing.allocation.enable: none
cluster.routing.allocation.cluster_concurrent_rebalance: 1
cluster.routing.allocation.node_concurrent_recoveries: 1

bootstrap.mlockall: true
path.data: {{data_paths}}
path.logs: /data1/logs
cloud:
    aws:
        region: us-west-2
        protocol: https
        ec2:
            protocol: https
discovery.type: ec2
discovery.zen.ping.multicast.enabled: false
discovery.zen.minimum_master_nodes: 1

index.number_of_shards: 1
index.number_of_replicas: 1
index.cache.field.type: soft
index.translog.interval: 60s
index.translog.flush_threshold_size: 1gb

indices.memory.index_buffer_size: 20%
indices.recovery.concurrent_streams: 1
indices.recovery.max_bytes_per_sec: 1000mb
indices.store.throttle.type: none

http.compression: true
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
http.compression: true
http.max_content_length: 1000mb
http.timeout: 600

threadpool.bulk.queue_size: 3000
threadpool.index.queue_size: 1000
